name = input('What is your name?')
age = int(input('what is your age?'))
university = input('Where do you study?')
degree = input('What do you study?') 
semester = input('What is your current semester?')
favourite_programming_language = input('What is your favourite programming language?')
goal = input('What is your career goal?')

print('====================================================')
print('                Student Information                 ')
print('====================================================')
print(f'Name: {name}.')
print(f'Age: {age}.')
print(f'University: {university}.')
print(f'Degree: {degree}.')
print(f'Semester: {semester}.')
print(f'Favourite Language: {favourite_programming_language}.')
print(f'Career Goal: {goal}.')
print('====================================================')